name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run nix-darwin -- build --flake .#mbp
      - run: nix flake check
